### PR TITLE
Fix file truncation

### LINKED ISSUE #65: Truncation fails if new size is larger than the current file size
As [FileChannel.html#truncate()](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/nio/channels/FileChannel.html#truncate(long)) of the Java NIO API doesn't follow the POSIX standard by not extending a file if it is shorter (by using zero bytes), we run into the following issue https://github.com/cryptomator/cryptomator/issues/2218

From the doc: 

>  If the given size is less than the file's current size then the file is truncated, discarding any bytes beyond the new end of the file. If the given size is greater than or equal to the file's current size then the file is not modified. In either case, if this channel's file position is greater than the given size then it is set to that size. 

of https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/nio/channels/FileChannel.html#truncate(long)

### PR DESCRIPTION
**Pull request by SailReal**
Fixes #65

### CODE REVIEW

File: src/main/java/org/cryptomator/frontend/fuse/OpenFile.java [hunk 1]
```diff
@@ -108,7 +108,7 @@ public void fsync(boolean metaData) throws IOException {
 	}
 
 	public void truncate(long size) throws IOException {
-		channel.truncate(size);
+		TruncateOrExpandFileChannelUtility.execute(channel, size);
```
Comment (overheadhunter) [inline src/main/java/org/cryptomator/frontend/fuse/OpenFile.java:111]: Just a naming suggestion:

`FileChannelUtil.truncateOrExpand(channel, size)`

File: pom.xml [hunk 2]
```diff
@@ -109,6 +109,11 @@
 			<version>${mockito.version}</version>
 			<scope>test</scope>
 		</dependency>
+		<dependency>
+			<groupId>org.mockito</groupId>
+			<artifactId>mockito-inline</artifactId>
+			<version>${mockito.version}</version>
+		</dependency>
```
Comment (overheadhunter) [inline pom.xml:116]: Isn't the MockMaker included in Mockito 4.x?

Comment (SailReal) [reply pom.xml:116]: Yes, just removed the [org.mockito.plugins.MockMaker](https://github.com/cryptomator/fuse-nio-adapter/pull/66/commits/3edcab74dce506dcb3c6065468bd09213e1b63a9#diff-b8f025a6bc4fe418ee263e43aeb2678327f367a433bd2792d191f7a7f893775b) file, thanks for mentioning. `mockito-inline` is still required, otherwise the new tests fails with `Mockito can only mock non-private & non-final classes.`.

File: src/main/java/org/cryptomator/frontend/fuse/OpenFile.java (hunk 1 above)
Comment (SailReal) [reply src/main/java/org/cryptomator/frontend/fuse/OpenFile.java]: :+1: applied it in https://github.com/cryptomator/fuse-nio-adapter/pull/66/commits/f41ec90f725cdee3deff9808488619ce864e224a

File: pom.xml (hunk 2 above)
Comment (overheadhunter) [reply pom.xml:116]: strange, I can't recall adding this dependency in any other repo, such as cryptofs, despite heavily mocking basically everything
