### PR TITLE
Cancel regular unmount if filesystem is still in use

### LINKED ISSUE #47: Check for openFileHandles before regular unmount to cancel it
If a file channel is still open when one executes the unmount method ( which in the end calls the linux helper command `fusermount`), the unmount fails with a `CommandFailedException`:
https://github.com/cryptomator/fuse-nio-adapter/blob/4bb19ad6dd99598c6502944eedf4988445ba48a9/src/main/java/org/cryptomator/frontend/fuse/mount/AbstractMount.java#L46-L53

Nonetheless, with the call `fuseAdapter.unmount()` the actual filesystem is marked as not-mounted, make it impossible to recover from the failed regular unmount command:
https://github.com/cryptomator/fuse-nio-adapter/blob/4bb19ad6dd99598c6502944eedf4988445ba48a9/src/main/java/org/cryptomator/frontend/fuse/ReadOnlyAdapter.java#L266-L273

Additionally, the `CommandFailedException` for the `fusermount` only means that the operation did not succeeded, but does not indicate for what reason.

I propose to change the regular unmount to _ only_ execute `fusermount` and marking the filesystem as unmounted, if no internal file channels are open and otherwise throw a different exception. If the filesystem need to be unmoutned, the `unmountForced()` method can be used.

Ideas how to implement can be taken from https://github.com/cryptomator/dokany-nio-adapter/commit/9a65c64169dc3662d9cd1bf699ad0207d4034f6d

### PR DESCRIPTION
**Pull request by infeo**
This PR closes #47.

It adds the method `isNotSafeToUnmount()` to `FuseNioAdapter`, to indicate wether the filesystem is in a state where the (internal) regular unmount method should be called.

To achieve this, the number of open files is checked and wether there is a pending (path locking) file system operation.

### CODE REVIEW

File: src/main/java/org/cryptomator/frontend/fuse/FuseNioAdapter.java [hunk 1]
```diff
@@ -6,6 +6,19 @@
...
+	 *
+	 * Important: This function only checks if it is _not_ safe and a return value of {@code false} should not be considered as an unmount can be safely executed.
+	 * The file system may be in state where it cannot be determined, hence this method returns false.
+	 *
+	 * API note: It is the task of the fs developer to decide what "not safe" means. For example, "not safe" can mean there are open resources or pending operations.
+	 * Additionally no guarantees about the validity of the result after the call is made, i.e. the result may be immediately outdated.
+	 *
+	 * @return true if the filesystem is in a state, where an unmount should not be performed.
+	 */
+	boolean isNotSafeToUnmount();
```
Comment (overheadhunter) [inline src/main/java/org/cryptomator/frontend/fuse/FuseNioAdapter.java:20]: This is a highly specific method name, suggesting it is only useful for one purpose (i.e. in preparation of unmount). I'd prefer a more generic name, if this is exposed via an public API rather than an unmount-specific internal behaviour.

I'd suggest `isInUse` as it is easy to understand that returning "false" does not make any promises that it is _not_ in use.

File: src/main/java/org/cryptomator/frontend/fuse/locks/PathLockBuilder.java [hunk 2]
```diff
@@ -4,6 +4,10 @@
 
 	PathLock forReading();
 
+	PathLock tryForReading() throws AlreadyLockedException;
+
 	PathLock forWriting();
 
+	PathLock tryForWriting() throws AlreadyLockedException;
+
```
Comment (overheadhunter) [inline src/main/java/org/cryptomator/frontend/fuse/locks/PathLockBuilder.java:12]: This is a significant change that should be covered by tests!

Comment (infeo) [reply src/main/java/org/cryptomator/frontend/fuse/locks/PathLockBuilder.java:12]: Done by ce4c76a404eab879af6468d982328630a92fb711

File: src/main/java/org/cryptomator/frontend/fuse/FuseNioAdapter.java (hunk 1 above)
Comment (infeo) [reply src/main/java/org/cryptomator/frontend/fuse/FuseNioAdapter.java]: Done with c4e741f832c42f6ffa99e8af5ab11eb4b9b5c65b

File: src/test/java/org/cryptomator/frontend/fuse/locks/LockManagerTest.java [hunk 3]
```diff
@@ -127,6 +127,56 @@ public void testMultipleWriteLocks() {
...
+			AtomicInteger exceptionCounter = new AtomicInteger();
+
+			try (PathLock lock = lockManager.createPathLock("/foo/bar/baz").forWriting()) {
+				for (int i = 0; i < numThreads; i++) {
+					int threadnum = i;
+					threadPool.submit(() -> {
+						if (threadnum % 2 == 0) {
+							try (PathLock lockThread = lockManager.createPathLock("/foo/bar/baz").tryForWriting()) {
+								counter.incrementAndGet();
+								Thread.sleep(10);
```
Comment (overheadhunter) [inline src/test/java/org/cryptomator/frontend/fuse/locks/LockManagerTest.java:148]: why sleep?
why 4 threads? one for read, one for write should be sufficient..?

File: src/test/java/org/cryptomator/frontend/fuse/locks/LockManagerTest.java [hunk 4]
```diff
@@ -127,6 +127,56 @@ public void testMultipleWriteLocks() {
...
+								maxCounter.set(Math.max(counter.get(), maxCounter.get()));
```
Comment (overheadhunter) [inline src/test/java/org/cryptomator/frontend/fuse/locks/LockManagerTest.java:149]: what is the purpose of `maxCounter` (btw this is not an atomic operation)

**Review by overheadhunter — COMMENTED** [review]
I believe the test can be simplified

**Review by overheadhunter — APPROVED** [review]
